vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO crud89/litefx
  REF 2d7e5b8440625d4625f5b8c2ae529f2c3fa5567a
  SHA512 04b20e16f22a29da74e62a5c031b8118c9a603ae8ca6867436a4f418a7d7a96e09bc263a2f7873ade5d9dfc39efdf36499fb69c5b1714a2c49f1370183e974b6
  HEAD_REF release/0.4
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        dx12          LITEFX_BUILD_DIRECTX_12_BACKEND
        vulkan        LITEFX_BUILD_VULKAN_BACKEND
        glm           LITEFX_BUILD_WITH_GLM
        dx-math       LITEFX_BUILD_WITH_DIRECTX_MATH
        pix-support   LITEFX_BUILD_WITH_PIX_RUNTIME
        debug-markers LITEFX_BUILD_SUPPORT_DEBUG_MARKERS 
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}/src
    OPTIONS 
        -DCMAKE_INSTALL_INCLUDEDIR=include/
        -DLITEFX_BUILD_EXAMPLES=OFF
        -DLITEFX_BUILD_TESTS=OFF
        ${FEATURE_OPTIONS} 
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH cmake/)

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
file(REMOVE "${CURRENT_PACKAGES_DIR}/LICENSE" "${CURRENT_PACKAGES_DIR}/NOTICE" "${CURRENT_PACKAGES_DIR}/debug/LICENSE" "${CURRENT_PACKAGES_DIR}/debug/NOTICE")
