vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO crud89/litefx
  REF 37afb656549679e34150cd4a6cdd2bfe739678ee
  SHA512 c56a2fba8692a1e4d9f9b1f119d9984fb616dbbba19b32a9b57d1256c73231dbce37bf4ec27e8e5a6a9d63da38803da84752fa0cc7b15d5fac552a90d8aad85c
  HEAD_REF main
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        dx12          LITEFX_BUILD_DIRECTX_12_BACKEND
        vulkan        LITEFX_BUILD_VULKAN_BACKEND
        glm           LITEFX_BUILD_WITH_GLM
        dx-math       LITEFX_BUILD_WITH_DIRECTX_MATH
        pix-support   LITEFX_BUILD_WITH_PIX_RUNTIME
        debug-markers LITEFX_BUILD_SUPPORT_DEBUG_MARKERS 
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}/src
    OPTIONS 
        -DCMAKE_INSTALL_INCLUDEDIR=include/
        -DLITEFX_BUILD_EXAMPLES=OFF
        -DLITEFX_BUILD_TESTS=OFF
        ${FEATURE_OPTIONS} 
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH cmake/)

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
file(REMOVE "${CURRENT_PACKAGES_DIR}/LICENSE" "${CURRENT_PACKAGES_DIR}/NOTICE" "${CURRENT_PACKAGES_DIR}/debug/LICENSE" "${CURRENT_PACKAGES_DIR}/debug/NOTICE")
